# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chatfe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chatfe
  pod 'TTTAttributedLabel'
  pod 'IntroScreen'
  pod 'MBProgressHUD'
  pod 'CircularCarousel'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'
  pod 'Kingfisher'
  pod 'DropDown'

  target 'ChatfeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatfeUITests' do
    # Pods for testing
  end

end
