# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Chatfe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chatfe
	pod 'IQKeyboardManager' 
	pod 'MBProgressHUD'
	pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Kingfisher'
  pod 'DropDown'
  pod 'CalendarKit'
  pod 'TagListView', '~> 1.0'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod "ReactionButton"

  target 'ChatfeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatfeUITests' do
    # Pods for testing
  end

end
